### ISSUE TITLE
Migration: support class rename

### ISSUE THREAD

**Issue by MarcusDenker** [ApptiveGrid/Soil#102]
When classes are renamed during development, but data is already stored in the database, we can not read that data currently

We need to somehow model the "rename class" refactoring"

This is not that easy:
- Git does not model any data that knows that a class was renamed
- There is some support in Epicea, but epicea data is just stored on the local disk of the developer

One idea could be to, as a first step, rely on deprecated classes:

- every time a class is renamed, the developer adds an empty subclass that implements #isDeprecated on the class side
- that method could have a pragma <deprecatedWithNewName: #NewClassName>

Now the materializer would have all the information to load the old data on disk

**Comment by noha** [comment]
I did not expect something magic happening here. In Soil there could be a SoilRefactoring class that someone can use the change the shape of a class. Using the tool we could generate information about the refactoring and store it somewhere so it can be picked up by Soil. 
This could be a class side method with a known name that is generated from the shape change or something comparable
