### ISSUE TITLE
Migration: support changing class Layouts

### ISSUE THREAD

**Issue by MarcusDenker** [ApptiveGrid/Soil#105]
A change that does not happen that often is to change class so that the Class Layout is another one.

e.g. you start with a Array like class that is VariableLayout and change it to a FixedLayout. Or a non-pointer layout to a pointer layout.

In some cases, not much can be done, data will always get lost, but at least we should be able to create some objects without an error (but maybe a log entry)

**Comment by noha** [comment]
I think the idea was to think about and confirm that it is not possible. In that case a log message plus error would be a good option to fulfill the task

**Comment by noha** [comment]
@MarcusDenker Is this done?
