### ISSUE TITLE
Migration: test migration with multiple intermediate versions

### ISSUE THREAD

**Issue by MarcusDenker** [ApptiveGrid/Soil#106]
PointerLayout>>#updateIvars:with:for: checks multiple behavior versions

- add a test that tests this scenario

Do we really need it? There is one last state in the database, and one current version of code. (all the changes that where done by the developer are not known to the database and not known to the image that now loads that database?)

**Comment by noha** [comment]
Yes, don't think that all objects are converted all the time. If the code changes frequently and new objects are written you end up with probably objects that are 10 versions back
