### ISSUE TITLE
Add Btree+ index

### ISSUE THREAD

**Issue by noha** [ApptiveGrid/Soil#121]

**Comment by MarcusDenker** [comment]
TODO:

- [ ] Test:  Index Split when rootpage is full
- [ ] Test: index Split of non-root page
- [ ] Storage is incomplete (misses items write, tests)
- [ ] For loading we need to add pageCode support to be able to load index pages
- [ ] Test: write btree with index+multiple data pages
- [ ] removal not yet supported

DONE:

- [ ]  we can add to the data page
- [ ] data page split adds index entry
- [ ] index is used for at: and at:put:
- [ ] #size: implemented in iterator and test

**Comment by noha** [comment]
Those todo entries should be issues
