### ISSUE TITLE
delegate to class and let the class decide what to do

### ISSUE THREAD

**Issue by vonbecmann** [ApptiveGrid/Soil#138]
Actual:
```
Object >> soilBasicSerialize: serializer [
	"Delegate serialization to the class layout"
	self class classLayout soilBasicSerialize: self with: serializer
]
```
you early decide what to do instead delegate to class and then let the class decide what to do.
also it can break, because it's a long statement deciding everything. 

Expected:
```
Object >> soilBasicSerialize: serializer [
	"Delegate serialization to the class"
	self class soilBasicSerialize: self with: serializer
]
```

```
Object class >> soilBasicSerialize: anObject with: serializer [
	"Delegate serialization to the classLayout"
	self classLayout soilBasicSerialize: anObject with: serializer
]
```
just a point of view. an opinion. thanks

**Comment by vonbecmann** [comment]
more pushing forward than pulling.
the same happens with 
```
soilSerializeBehaviorDescription: anObject with: serializer
	| description |
	description := serializer behaviorDescriptionFor: anObject class.
	serializer
		nextPutObjectType;
		nextPutLengthEncodedInteger: (description referenceIndexWithSerializer: serializer).
	^ description
```
this method could delegate to the serializer
```
serializer serializeBehaviorDescriptionFor: anObject
```

**Comment by MarcusDenker** [comment]
The first one, we do not want to forward to the class, because it makes no sense to override there.

-> per class, you can implement your special serialisation, by overriding #soilBasicSerialize: , if you do not, then we exactly want to forward to the *layout*. Now there is no method Object>>#classLayout, so we have to do "class classLayout".

For the second suggestion, yes, I did that in the PR #183

**Comment by vonbecmann** [comment]
> Now there is no method Object>>#classLayout, so we have to do "class classLayout".
right, you put the #soilBasicSerialize: method on the class side and then you can send the message to classLayout
