### ISSUE TITLE
commit does not work on subsequent calls of Soil class>>#path:

### ISSUE THREAD

**Issue by yannij** [ApptiveGrid/Soil#154]
Two test cases are attached. One is a slightly modified version of the other, to make it pass. The difference is that in the working version the whole root object is written using the original Soil instance created with #initializeFilesystem. In the failing version, the code commits a new Dictionary instance, then opens a new Soil instance to add objects to that pre-saved initial root.
[SoilTest-testSerializingToSavedRootWorks.st.txt](https://github.com/ApptiveGrid/Soil/files/10453711/SoilTest-testSerializingToSavedRootWorks.st.txt)
[SoilTest-testSerializingToSavedRoot.st.txt](https://github.com/ApptiveGrid/Soil/files/10453712/SoilTest-testSerializingToSavedRoot.st.txt)

**Comment by noha** [comment]
I linked to PR that fixes it. You need to open soil properly. And you've forgot to do a markDirty: on the root after modifying

**Comment by noha** [comment]
Now there is a problem with objectids and the index. Try to solve tomorrow. Too much refactoring lately 🗡️

**Comment by yannij** [comment]
Strangely, the instance side setter method Soil>>#path: is doing a "self open".

**Comment by noha** [comment]
That I just removed because it does not belong to there

**Comment by noha** [comment]
The PR build is green. There was lots of changes which are now nearly done and I start improving the individual parts
