### ISSUE TITLE
Sometimes failing: SOFileLockRegistryTest>>#testAcquireAndGarbageCollect

### ISSUE THREAD

**Issue by MarcusDenker** [ApptiveGrid/Soil#180]
When running all tests of in Soil-File-Tests, 

 SOFileLockRegistryTest>>#testAcquireAndGarbageCollect

fails sometimes. It is green when running it alone

**Comment by noha** [comment]
This is something not necesarily guaranteed with pharo10. But with ephemerons my understanding is that it should be reliable

**Comment by MarcusDenker** [comment]
this was fixed by https://github.com/ApptiveGrid/Soil/pull/248
