### ISSUE TITLE
soilLoadedIn: vs soilMaterialized:

### ISSUE THREAD

**Issue by MarcusDenker** [ApptiveGrid/Soil#197]
soilMaterialized: is sent to every object after we materialize it.

In addition, there is #soilLoadedIn:, it has no senders. 

-> when do we want to sent this?

**Comment by noha** [comment]
These are life cycle methods for user objects. Sometimes it is necessary to know which transactions an object is loaded/materialized in. Therefor the objects should be called at the specific points in the life cycle.

**Comment by noha** [comment]
But yes soilLoadedIn: is really helpful. Not so sure about soilMaterialized: I remembered adding this when using fuel because it was the only way injectiong the transaction
