### ISSUE TITLE
Pharo11: SOFileLockRegistryTest>>#testAcquireAndGarbageCollect 

### ISSUE THREAD

**Issue by MarcusDenker** [ApptiveGrid/Soil#232]
SOFileLockRegistryTest>>#testAcquireAndGarbageCollect  is failing on Pharo11

**Comment by MarcusDenker** [comment]
this version is green on Pharo11 even when running all tests in the testrunner together:\

- SOFileLockRegistry numberOfRegistries can be larger than 1 as finalization might not yet have happend from other tests
- do GC until the registries are all gced (3 might not be enough)

```
testAcquireAndGarbageCollect
	| registry |
	registry := SOFileLockRegistry forPath: '/tmp/foo'.
	self assert: registry numberOfLocks equals: 0.
	self assert: SOFileLockRegistry numberOfRegistries > 0.
	registry := nil.
	[  SOFileLockRegistry numberOfRegistries = 0 ] whileFalse: [ Smalltalk garbageCollect ].

	"The registry should have been vanished"
	self assert: SOFileLockRegistry numberOfRegistries equals: 0.
```

**Comment by noha** [comment]
It looks a bit like a good source for an endless loop. But as this is a test it might be good. How about making a PR?
