### ISSUE TITLE
[Serializer] WideString/Symbol: Do we have to encode?

### ISSUE THREAD

**Issue by MarcusDenker** [ApptiveGrid/Soil#259]
We now encode WideStrings and WideSymbols using the ZnCharacterEncoder 

This is configurable per image for WideString to be utf8/16/32, for WideSymbol we use #utf8.

The question is: do we really need to encode? With the Serializer, we want to write WideStrings to disk and read them. The data on disk is always read by Soil with Pharo, there will never be the need for the data on disk to be read by non-Pharo clients.

Encoding seems to just make that data smaller. We could just store the WideString directly without encoding it first.

- asByteArray uses a primitive and thus much faster
- Simpler
- less code
	
negative:
- Wide Strings and Symbols would be larger on disk

**Comment by noha** [comment]
Yes we could. But it should be a configuration option. WideString natively read/written could be faster but uses more space. If this is variable length encoded then for western charsets it could also be small. Depends on the memory representation of a wide string
