### ISSUE TITLE
BTree: add space for lastFreePageIndex

### ISSUE THREAD

**Issue by MarcusDenker** [ApptiveGrid/Soil#629]
For BTree, we the only difference is that we have to maintain two kinds of pages: data and index pages.

- SoilBTreeHeaderPage would store the lastFreePageIndex just like the skipList
- The SoilBTreeRootPage would store a page that manages the unused index pages

For the index pages, they are not concatenated, thus we cannot point to the last unused page. Instead, we need to use the unused page to store more un-used pages (if there are more than one). 
- if unused page is empty, re-use that
- if not, this page forms a tree index of unused index pages (with the leafs being empty, ready for reuse)

**Comment by MarcusDenker** [comment]
SoilBTreeHeaderPage is done with #627

**Comment by noha** [comment]
This is what I told you. We need free pages and free page list pages, the ones that are free and the ones that lists pages that are free
