### ISSUE TITLE
Github: protect development branch

### ISSUE THREAD

**Issue by MarcusDenker** [ApptiveGrid/Soil#63]
GitHub is now suggesting to use protected branches for the development branch. 

This then allows us to add rules, e.g. merge only after one review

**Comment by noha** [comment]
That's what we do anyway and enforcing is a poor replacement for this. It just restricts possibilities and if I have a hotfix I don't want to be annoyed by a stupid machine that I cannot

**Comment by MarcusDenker** [comment]
Hotfix still is possible, admins can override.

I think the idea is that if you protect the branch, you can give write access to the repository which in turn them allows users to use the issue tracker for real. But that is more for bigger projects (like Pharo).

I will close this here
