### ISSUE TITLE
Define behavior descriptions and refactorings

### ISSUE THREAD

**Issue by noha** [ApptiveGrid/Soil#71]
Behavior descriptions are snapshots of the class shape and properties. What do we want to store in the database about a class version?

- instVarNames
- instVarOrder
- class name
- reified refactoring from last version
- ??

**Comment by MarcusDenker** [comment]
is this really done?

**Comment by noha** [comment]
No, I think I've put the wrong number in the commit message

**Comment by MarcusDenker** [comment]
I added for the refactorings:

- Migration: support instance variable rename #103
- Migration: support class rename #102

**Comment by MarcusDenker** [comment]
- Migration: support changing class Layouts #105

**Comment by MarcusDenker** [comment]
added issue about multiple versions:

- Migration: test migration with multiple intermediate versions #106

I think with this all the TODOs are covered and we can close this issue
