### ISSUE TITLE
SoilObjectProxy should forward #class

### ISSUE THREAD

**Issue by MarcusDenker** [ApptiveGrid/Soil#820]
Due to SoilObjectProxy inheriting from ProtoObject, #class is not forwarded.

This can be a problem as #class is quite common in user code (e.g. it is a common way to implement #=).

We should think about implementing #class at the level of the Proxy

```
class
    ^ self soilRealObject class
```

The PR https://github.com/ApptiveGrid/Soil/pull/819 makes sure we do not use it internally anymore.

**Comment by MarcusDenker** [comment]
The problem is that #class is used in client code (e.g. very common in #= methods). 

e.g. adding an object that overrides #= to a OrdereCollection and making it a root then does not work, as the OrdereCollection used #= e.g. when removing.

**Comment by MarcusDenker** [comment]
Here is an example:

We store a OrderedCollection with one RBComment inside that we make a root:
```
db := Soil ensureOnPath: './test.soil'.
tx := db newTransaction.
collection := OrderedCollection new.
tx root: collection.
objectUsingClassinQueals :=  RBComment with: (RBCommentToken value: 'Some sample text' start: 5 stop: 21).
tx makeRoot: objectUsingClassinQueals. 
collection add: objectUsingClassinQueals.
tx markDirty: objectUsingClassinQueals.
tx markDirty: collection.
tx commit.

"now lets try to remove the object in a new transaction, note that the #remove uses #= which sends #class"
tx := db newTransaction.
tx root
    remove: objectUsingClassinQueals.
tx commit.

```

**Comment by noha** [comment]
ok ok :D Need to check apptive if we fall over then
